//***************************** Stories.jsx *********************************
//* Displays user and friends' stories with optimized video thumbnails based on screen size
// - local file on user's device
// - thumbnail can be generated client-side from the local file (blob URL)
// - tools needed : JavaScript/Canvas API or custom librairies
//****************************************************************************

import { useContext, useState, useEffect } from "react";
import "./stories.scss";
import { useQuery } from "@tanstack/react-query";
import { makeRequest } from "../../utils/axios.js";
import { isImage, isVideo } from "../../utils/isFile.js";

// Components
import CreateStory from "./CreateStory.jsx";
import ModalStory from "./ModalStory.jsx";
import LazyLoadImage from "../lazyLoadImage/LazyLoadImage.jsx";
import Loader from "../loader/Loader.jsx";

// Image
import defaultProfile from "../../assets/images/users/defaultProfile.jpg";

// Context
import { AuthContext } from "../../contexts/authContext.jsx";

export default function Stories({ userId }) {
  const { currentUser } = useContext(AuthContext);
  const [openCreateStory, setOpenCreateStory] = useState(false);
  const [openModal, setOpenModal] = useState(false);
  const [selectedStory, setSelectedStory] = useState(null); // State to detect small screen size (e.g., mobile)
  const [isSmallScreen, setIsSmallScreen] = useState(window.innerWidth < 600);

  // Hook to detect screen resize and update isSmallScreen state
  useEffect(() => {
    const handleResize = () => {
      setIsSmallScreen(window.innerWidth < 600);
    };
    // Set up the event listener
    window.addEventListener("resize", handleResize);

    // Cleanup the event listener on component unmount
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  // Get stories data
  const fetchStories = async () => {
    try {
      const res = await makeRequest.get(`/stories?userId=${userId}`);
      return res.data;
    } catch (error) {
      console.error("Error fetching stories:", error);
    }
  };

  const {
    isLoading,
    error,
    data: stories,
  } = useQuery({ queryKey: ["stories", userId], queryFn: fetchStories });

  // Handler to open the modal with the selected story
  const handleClick = (story) => {
    setSelectedStory(story);
    setOpenModal((prevState) => !prevState);
  };

  return (
    <>
      <div className="stories">
        {/* Stories wrapper */}
        <div className="stories-wrapper">
          {/* "Create a story" entry point */}
          <div className="story">
            <LazyLoadImage
              src={
                currentUser?.profilePic
                  ? //! "uploads" is the public web path that is exposed and handled by our web server for static assets
                    `/uploads/${currentUser.profilePic}`
                  : defaultProfile
              }
              alt="user"
            />
            <div className="add">Create a story</div>
            <button
              onClick={() => setOpenCreateStory((prevState) => !prevState)}
            >
              +
            </button>
          </div>

          {/* Display user and friends' stories */}
          {error ? (
            <span className="msg">Something went wrong</span>
          ) : isLoading ? (
            <Loader />
          ) : stories?.length === 0 ? (
            <span className="msg">No story to show yet.</span>
          ) : (
            // Map through and display all available stories
            stories?.map((story) => {
              // 1 - DEFINE THE THUMBNAIL PATH
              // The backend saves the thumbnail as "/uploads/thumbnails/{storyId}.jpg"
              const thumbnailSrc = `/uploads/thumbnails/${story?.id}.jpg`;
              const fileSrc = `/uploads/${story?.file}`;

              return (
                <div
                  className="story"
                  key={story?.id}
                  onClick={() => handleClick(story)}
                  style={{ cursor: "pointer" }}
                >
                  {/* 2 - DISPLAY FILE BASED ON ITS EXTENSION */}
                  {isVideo(story?.file) ? (
                    // 2.1 - Conditional video story rendering
                    isSmallScreen ? (
                      // Small screen : Show the static thumbnail generated by the backend
                      <LazyLoadImage
                        src={thumbnailSrc}
                        alt="story video thumbnail"
                      />
                    ) : (
                      // Large screen : Show video tag with the static thumbnail as poster
                      <video muted loop poster={thumbnailSrc}>
                        <source
                          src={fileSrc} // Use original video file for playback
                          type={
                            // Simplification to generic video type, assuming modern formats
                            story?.file.toLowerCase().endsWith(".mov")
                              ? "video/quicktime"
                              : `video/${story?.file.split(".").pop()}`
                          }
                        />
                        Your browser doesn't support video.
                      </video>
                    )
                  ) : (
                    // 2.2 - Display image story                  (
                    isImage(story?.file) && (
                      // Use original file path
                      <LazyLoadImage src={fileSrc} alt="story" />
                    )
                  )}

                  <span>
                    {story?.firstName} {story?.lastName}
                  </span>
                </div>
              );
            })
          )}
        </div>
      </div>

      {/* Modals for creation and viewing */}
      {openCreateStory && (
        <CreateStory setOpenCreateStory={setOpenCreateStory} />
      )}
      {openModal && (
        <ModalStory story={selectedStory} setOpenModal={setOpenModal} />
      )}
    </>
  );
}
